spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/order_master?serverTimezone=GMT%2b8&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&autocommit=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://localhost:3306/order_slave?serverTimezone=GMT%2b8&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&autocommit=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
    level:
        cn.enjoyedu.rwseparation: DEBUG
    root: INFO